import { boolean, index, integer, pgTable, text, timestamp } from 'drizzle-orm/pg-core';

export const timeEntries = pgTable(
  'time_entries',
  {
    id: text('id').primaryKey(),
    assignmentId: text('assignment_id').notNull(),
    startedAt: timestamp('started_at', { withTimezone: true }).notNull(),
    endedAt: timestamp('ended_at', { withTimezone: true }),
    // Generated by the database, never written by us.
    durationSeconds: integer('duration_seconds'),
    source: text('source').notNull().default('timer'),
    reason: text('reason'),
    billable: boolean('billable').notNull().default(true),
    note: text('note'),
    approvedAt: timestamp('approved_at', { withTimezone: true }),
    approvedBy: text('approved_by'),
    statementLineId: text('statement_line_id'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index('time_entries_assignment_idx').on(table.assignmentId, table.startedAt)],
);

/** One row per person, by primary key. FR-21 as a constraint. */
export const runningTimers = pgTable('running_timers', {
  userId: text('user_id').primaryKey(),
  assignmentId: text('assignment_id').notNull(),
  startedAt: timestamp('started_at', { withTimezone: true }).notNull(),
  deviceId: text('device_id'),
  lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull(),
  heldAt: timestamp('held_at', { withTimezone: true }),
});
