import { type TestDatabase, createTestDatabase } from '@amc/database/testing';
import type { drizzle } from 'drizzle-orm/postgres-js';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { RunningTimer, TimeEntry } from '../domain/index.js';
import { DrizzleRunningTimerRepository, DrizzleTimeEntryRepository } from './time.repository.js';

const at = (iso: string) => new Date(iso);

/**
 * The driver wraps a database error in "Failed query: ...", so the message
 * that actually explains the refusal is further down the cause chain.
 */
async function refusalFor(work: () => Promise<unknown>): Promise<string> {
  try {
    await work();
  } catch (error) {
    // The wrapper keeps the original in its stack rather than always in a
    // cause, so both are searched.
    const parts: string[] = [];
    let current: unknown = error;
    while (current instanceof Error) {
      parts.push(current.message, current.stack ?? '');
      current = (current as { cause?: unknown }).cause;
    }
    return parts.join(' | ');
  }
  throw new Error('that was expected to be refused, and was not');
}

describe('recorded time against a real database', () => {
  let database: TestDatabase;

  beforeAll(async () => {
    database = await createTestDatabase();
  });

  afterAll(async () => {
    await database?.close();
  });

  /** A client, a subscription, a task, and two people assigned to it. */
  async function scenario(tx: unknown) {
    const db = tx as ReturnType<typeof drizzle>;

    for (const [id, name] of [
      ['user-a', 'Accountant A'],
      ['user-b', 'Accountant B'],
    ] as const) {
      await db.execute(
        `INSERT INTO users (id, email, display_name, password_hash)
         VALUES ('${id}', '${id}@activemanagement.ae', '${name}', 'x')`,
      );
    }
    await db.execute(`INSERT INTO clients (id, legal_name) VALUES ('c-1', 'Gulf Trading LLC')`);
    await db.execute(
      `INSERT INTO client_services (id, client_id, service, active_from)
       VALUES ('cs-1', 'c-1', 'monthly_accounting', '2026-01-01')`,
    );
    await db.execute(
      `INSERT INTO tasks (id, client_service_id, client_id, service, state)
       VALUES ('t-1', 'cs-1', 'c-1', 'monthly_accounting', 'in_progress')`,
    );
    await db.execute(
      `INSERT INTO task_assignments (id, task_id, user_id, role, assigned_at, assigned_by)
       VALUES ('as-a', 't-1', 'user-a', 'responsible', '2026-01-01', 'manager')`,
    );
    await db.execute(
      `INSERT INTO task_assignments (id, task_id, user_id, role, assigned_at, assigned_by)
       VALUES ('as-b', 't-1', 'user-b', 'collaborator', '2026-01-01', 'manager')`,
    );

    return {
      db,
      entries: new DrizzleTimeEntryRepository(db),
      timers: new DrizzleRunningTimerRepository(db),
    };
  }

  function entry(id: string, assignmentId: string, from: string, to: string) {
    const created = TimeEntry.fromTimer({
      id,
      assignmentId,
      startedAt: at(from),
      endedAt: at(to),
    });
    if (!created.ok) throw new Error('fixture');
    return created.value;
  }

  it('stores an entry and computes its length in the database', async () => {
    await database.inRollbackTransaction(async (tx) => {
      const { db, entries } = await scenario(tx);
      await entries.save(entry('e-1', 'as-a', '2026-04-01T09:00:00Z', '2026-04-01T10:30:00Z'));

      const [row] = await db.execute("SELECT duration_seconds FROM time_entries WHERE id = 'e-1'");
      // Generated by the database, so a timesheet is a sum rather than a
      // calculation repeated a thousand times.
      expect(Number((row as { duration_seconds: number }).duration_seconds)).toBe(5400);
    });
  });

  it('refuses manual time with no reason, whatever writes it', async () => {
    await database.inRollbackTransaction(async (tx) => {
      const { db } = await scenario(tx);
      await expect(
        db.execute(
          `INSERT INTO time_entries (id, assignment_id, started_at, ended_at, source)
           VALUES ('e-bad', 'as-a', now(), now() + interval '1 hour', 'manual')`,
        ),
      ).rejects.toThrow();
    });
  });

  it('refuses to bill time that was never approved', async () => {
    await database.inRollbackTransaction(async (tx) => {
      const { db } = await scenario(tx);
      await expect(
        db.execute(
          `INSERT INTO time_entries (id, assignment_id, started_at, ended_at, statement_line_id)
           VALUES ('e-bad', 'as-a', now(), now() + interval '1 hour', 'line-1')`,
        ),
      ).rejects.toThrow();
    });
  });

  /**
   * One refusal per test, on purpose.
   *
   * A failed statement aborts the whole Postgres transaction, so a second
   * attempt in the same test reports "transaction aborted" rather than the
   * rule that refused it, and the test would pass or fail for the wrong
   * reason.
   */
  async function billedEntry(tx: unknown) {
    const { db, entries } = await scenario(tx);
    const recorded = entry('e-1', 'as-a', '2026-04-01T09:00:00Z', '2026-04-01T10:30:00Z');
    recorded.approve('manager-1', at('2026-04-02T06:00:00Z'));
    recorded.includeInStatement('line-1', at('2026-04-03T06:00:00Z'));
    await entries.save(recorded);
    return { db, entries, recorded };
  }

  it('will not let invoiced time be re-timed, even straight through SQL', async () => {
    await database.inRollbackTransaction(async (tx) => {
      const { db } = await billedEntry(tx);

      // The domain refuses this already. The database refusing it too is what
      // turns "the application will not do that" into "it cannot happen".
      expect(
        await refusalFor(() =>
          db.execute(
            "UPDATE time_entries SET ended_at = ended_at + interval '2 hours' WHERE id = 'e-1'",
          ),
        ),
      ).toContain('on a statement and cannot be changed');
    });
  });

  it('will not let invoiced time be made non-billable', async () => {
    await database.inRollbackTransaction(async (tx) => {
      const { db } = await billedEntry(tx);
      expect(
        await refusalFor(() =>
          db.execute("UPDATE time_entries SET billable = false WHERE id = 'e-1'"),
        ),
      ).toContain('on a statement and cannot be changed');
    });
  });

  it('allows the release, which is the one permitted change', async () => {
    await database.inRollbackTransaction(async (tx) => {
      const { db, entries } = await scenario(tx);
      const recorded = entry('e-1', 'as-a', '2026-04-01T09:00:00Z', '2026-04-01T10:30:00Z');
      recorded.approve('manager-1', at('2026-04-02T06:00:00Z'));
      recorded.includeInStatement('line-1', at('2026-04-03T06:00:00Z'));
      await entries.save(recorded);

      recorded.releaseFromStatement('manager-1', at('2026-04-04T06:00:00Z'));
      await entries.save(recorded);

      // And is editable again, which is the point of releasing it.
      await db.execute("UPDATE time_entries SET billable = false WHERE id = 'e-1'");
      const found = await entries.findById('e-1');
      expect(found?.isLocked).toBe(false);
    });
  });

  it('totals a day in Dubai time rather than UTC', async () => {
    await database.inRollbackTransaction(async (tx) => {
      const { entries } = await scenario(tx);
      // Nine in the evening in Dubai is five in the afternoon UTC, still the
      // same day. Half past eight UTC is half past midnight the next day in
      // Dubai, and belongs to that day.
      await entries.save(entry('e-1', 'as-a', '2026-04-01T17:00:00Z', '2026-04-01T18:00:00Z'));
      await entries.save(entry('e-2', 'as-a', '2026-04-01T20:30:00Z', '2026-04-01T21:30:00Z'));

      const sheet = await entries.timesheet(
        'user-a',
        at('2026-03-31T00:00:00Z'),
        at('2026-04-03T00:00:00Z'),
      );
      expect(sheet.map((row) => row.day)).toEqual(['2026-04-01', '2026-04-02']);
    });
  });

  it('separates billable from non-billable on the timesheet', async () => {
    await database.inRollbackTransaction(async (tx) => {
      const { entries } = await scenario(tx);
      const billable = entry('e-1', 'as-a', '2026-04-01T09:00:00Z', '2026-04-01T10:00:00Z');
      const internal = entry('e-2', 'as-a', '2026-04-01T11:00:00Z', '2026-04-01T12:00:00Z');
      internal.setBillable(false, at('2026-04-01T12:00:00Z'));
      await entries.save(billable);
      await entries.save(internal);

      const [day] = await entries.timesheet(
        'user-a',
        at('2026-04-01T00:00:00Z'),
        at('2026-04-02T00:00:00Z'),
      );
      expect(day?.seconds).toBe(7200);
      expect(day?.billableSeconds).toBe(3600);
    });
  });

  it('finds the hours a statement should bill, and only those', async () => {
    await database.inRollbackTransaction(async (tx) => {
      const { entries } = await scenario(tx);

      const ready = entry('e-ready', 'as-a', '2026-04-01T09:00:00Z', '2026-04-01T10:00:00Z');
      ready.approve('manager-1', at('2026-04-02T06:00:00Z'));
      await entries.save(ready);

      // Not approved yet.
      await entries.save(
        entry('e-unapproved', 'as-a', '2026-04-01T11:00:00Z', '2026-04-01T12:00:00Z'),
      );

      // Approved but not billable.
      const internal = entry('e-internal', 'as-b', '2026-04-01T13:00:00Z', '2026-04-01T14:00:00Z');
      internal.setBillable(false, at('2026-04-01T14:00:00Z'));
      internal.approve('manager-1', at('2026-04-02T06:00:00Z'));
      await entries.save(internal);

      // Approved and already billed.
      const billed = entry('e-billed', 'as-a', '2026-04-01T15:00:00Z', '2026-04-01T16:00:00Z');
      billed.approve('manager-1', at('2026-04-02T06:00:00Z'));
      billed.includeInStatement('line-9', at('2026-04-03T06:00:00Z'));
      await entries.save(billed);

      const unbilled = await entries.unbilledForClient('c-1', at('2026-05-01T00:00:00Z'));
      expect(unbilled.map((row) => row.entryId)).toEqual(['e-ready']);
      expect(unbilled[0]?.userId).toBe('user-a');
      expect(unbilled[0]?.taskId).toBe('t-1');
    });
  });

  it('attributes hours through the assignment, so reassignment leaves them alone', async () => {
    await database.inRollbackTransaction(async (tx) => {
      const { db, entries } = await scenario(tx);
      await entries.save(entry('e-1', 'as-a', '2026-04-01T09:00:00Z', '2026-04-01T10:00:00Z'));

      // A hands the task over to B in May. March's hour stays A's.
      await db.execute(
        "UPDATE task_assignments SET unassigned_at = '2026-05-01' WHERE id = 'as-a'",
      );

      const forA = await entries.forUserBetween(
        'user-a',
        at('2026-04-01T00:00:00Z'),
        at('2026-05-01T00:00:00Z'),
      );
      expect(forA.map((e) => e.id)).toEqual(['e-1']);
    });
  });
});

describe('the running timer against a real database', () => {
  let database: TestDatabase;

  beforeAll(async () => {
    database = await createTestDatabase();
  });

  afterAll(async () => {
    await database?.close();
  });

  async function scenario(tx: unknown) {
    const db = tx as ReturnType<typeof drizzle>;
    await db.execute(
      `INSERT INTO users (id, email, display_name, password_hash)
       VALUES ('user-a', 'a@activemanagement.ae', 'Accountant A', 'x')`,
    );
    await db.execute(`INSERT INTO clients (id, legal_name) VALUES ('c-1', 'Gulf Trading LLC')`);
    await db.execute(
      `INSERT INTO client_services (id, client_id, service, active_from)
       VALUES ('cs-1', 'c-1', 'monthly_accounting', '2026-01-01')`,
    );
    for (const [taskId, assignmentId] of [
      ['t-1', 'as-1'],
      ['t-2', 'as-2'],
    ] as const) {
      await db.execute(
        `INSERT INTO tasks (id, client_service_id, client_id, service, state)
         VALUES ('${taskId}', 'cs-1', 'c-1', 'monthly_accounting', 'in_progress')`,
      );
      await db.execute(
        `INSERT INTO task_assignments (id, task_id, user_id, role, assigned_at, assigned_by)
         VALUES ('${assignmentId}', '${taskId}', 'user-a', 'responsible', '2026-01-01', 'manager')`,
      );
    }
    return { db, timers: new DrizzleRunningTimerRepository(db) };
  }

  it('keeps one timer per person, replacing rather than adding (FR-21)', async () => {
    await database.inRollbackTransaction(async (tx) => {
      const { db, timers } = await scenario(tx);

      await timers.start(
        RunningTimer.start({
          userId: 'user-a',
          assignmentId: 'as-1',
          now: at('2026-04-01T09:00:00Z'),
        }),
      );
      await timers.start(
        RunningTimer.start({
          userId: 'user-a',
          assignmentId: 'as-2',
          now: at('2026-04-01T10:00:00Z'),
        }),
      );

      const [row] = await db.execute('SELECT count(*)::text AS count FROM running_timers');
      expect((row as { count: string }).count).toBe('1');

      const running = await timers.forUser('user-a');
      expect(running?.assignmentId).toBe('as-2');
    });
  });

  it('records a heartbeat, and finds the timers that have gone quiet', async () => {
    await database.inRollbackTransaction(async (tx) => {
      const { timers } = await scenario(tx);
      await timers.start(
        RunningTimer.start({
          userId: 'user-a',
          assignmentId: 'as-1',
          now: at('2026-04-01T09:00:00Z'),
        }),
      );

      await timers.beat('user-a', at('2026-04-01T09:30:00Z'));
      expect(await timers.stale(at('2026-04-01T09:15:00Z'))).toHaveLength(0);
      expect(await timers.stale(at('2026-04-01T11:00:00Z'))).toHaveLength(1);
    });
  });

  it('stops an abandoned timer at its last heartbeat rather than billing the night', async () => {
    await database.inRollbackTransaction(async (tx) => {
      const { timers } = await scenario(tx);
      await timers.start(
        RunningTimer.start({
          userId: 'user-a',
          assignmentId: 'as-1',
          now: at('2026-04-03T09:00:00Z'),
        }),
      );
      await timers.beat('user-a', at('2026-04-03T18:00:00Z'));

      const [abandoned] = await timers.stale(at('2026-04-06T08:00:00Z'));
      const trimmed = abandoned?.stopAsAbandoned();
      expect(trimmed?.endedAt.toISOString()).toBe('2026-04-03T18:00:00.000Z');
    });
  });

  it('clears the timer when it stops', async () => {
    await database.inRollbackTransaction(async (tx) => {
      const { timers } = await scenario(tx);
      await timers.start(
        RunningTimer.start({
          userId: 'user-a',
          assignmentId: 'as-1',
          now: at('2026-04-01T09:00:00Z'),
        }),
      );
      await timers.clear('user-a');
      expect(await timers.forUser('user-a')).toBeNull();
    });
  });

  it('survives a hold, keeping the task and counting nothing', async () => {
    await database.inRollbackTransaction(async (tx) => {
      const { timers } = await scenario(tx);
      const running = RunningTimer.start({
        userId: 'user-a',
        assignmentId: 'as-1',
        now: at('2026-04-01T09:00:00Z'),
      });
      await timers.start(running);

      running.hold(at('2026-04-01T09:40:00Z'));
      await timers.save(running);

      const reloaded = await timers.forUser('user-a');
      expect(reloaded?.isHeld).toBe(true);
      expect(reloaded?.assignmentId).toBe('as-1');
      expect(reloaded?.elapsedAt(at('2026-04-01T18:00:00Z')).seconds).toBe(0);
    });
  });

  it('counts from the resume, not from the original start', async () => {
    await database.inRollbackTransaction(async (tx) => {
      const { timers } = await scenario(tx);
      const running = RunningTimer.start({
        userId: 'user-a',
        assignmentId: 'as-1',
        now: at('2026-04-01T09:00:00Z'),
      });
      await timers.start(running);
      running.hold(at('2026-04-01T09:40:00Z'));
      await timers.save(running);

      const held = await timers.forUser('user-a');
      held?.resume(at('2026-04-01T11:00:00Z'));
      if (held) await timers.save(held);

      const resumed = await timers.forUser('user-a');
      expect(resumed?.isHeld).toBe(false);
      // Ten minutes, not the two hours and ten since it first started.
      expect(resumed?.elapsedAt(at('2026-04-01T11:10:00Z')).seconds).toBe(600);
    });
  });

  it('leaves held timers out of the sweep for abandoned ones', async () => {
    await database.inRollbackTransaction(async (tx) => {
      const { timers } = await scenario(tx);
      const running = RunningTimer.start({
        userId: 'user-a',
        assignmentId: 'as-1',
        now: at('2026-04-01T09:00:00Z'),
      });
      await timers.start(running);
      running.hold(at('2026-04-01T09:40:00Z'));
      await timers.save(running);

      // Long past any heartbeat deadline. A held timer still has nothing to
      // trim, and sweeping it would only lose the task somebody paused.
      const stale = await timers.stale(at('2026-04-09T00:00:00Z'));
      expect(stale.map((timer) => timer.userId)).not.toContain('user-a');
    });
  });

  it('refuses a hold recorded before the span it belongs to', async () => {
    await database.inRollbackTransaction(async (tx) => {
      const { db, timers } = await scenario(tx);
      await timers.start(
        RunningTimer.start({
          userId: 'user-a',
          assignmentId: 'as-1',
          now: at('2026-04-01T09:00:00Z'),
        }),
      );

      // The domain will not produce this. The database refuses it anyway,
      // because what the schema permits is what eventually arrives.
      await expect(
        db.execute(
          `UPDATE running_timers SET held_at = '2026-03-01T09:00:00Z' WHERE user_id = 'user-a'`,
        ),
      ).rejects.toThrow();
    });
  });
});
